# @config-manager:start frontend-top-level
'oxc.fmt.configPath' = '.oxfmtrc.jsonc'
# @config-manager:end frontend-top-level

# @config-manager:start frontend
['[javascript]']
  'editor.defaultFormatter' = 'oxc.oxc-vscode'
  'editor.formatOnSave' = true
['[javascriptreact]']
  'editor.defaultFormatter' = 'oxc.oxc-vscode'
  'editor.formatOnSave' = true
['typescript]']
  'editor.defaultFormatter' = 'oxc.oxc-vscode'
  'editor.formatOnSave' = true
  # @config-manager:end frontend
