---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

# @config-manager:start workflow-name
# @config-manager:end workflow-name

on:
  # @config-manager:start workflow-on
  # @config-manager:end workflow-on

concurrency:
  # @config-manager:start workflow-concurrency
  # @config-manager:end workflow-concurrency

# Declare default permissions as read only.
# @config-manager:start workflow-permissions
# @config-manager:end workflow-permissions

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      # @config-manager:start workflow-permissions-job
      # @config-manager:end workflow-permissions-job
    steps:
      # @config-manager:start workflow-steps
      # @config-manager:end workflow-steps
