---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

# @config-manager:start workflow-name
# @config-manager:end workflow-name

# @config-manager:start workflow-on
# @config-manager:end workflow-on

# @config-manager:start workflow-permissions
# @config-manager:end workflow-permissions

# @config-manager:start workflow-concurrency
# @config-manager:end workflow-concurrency

jobs:
  analysis:
    name: Perform analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      # @config-manager:start workflow-permissions-job
      # @config-manager:end workflow-permissions-job
      # Uncomment the permissions below if installing in a private repository.
      # contents: read
      # actions: read

    steps:
      # @config-manager:start harden-runner
      # @config-manager:end harden-runner
      # @config-manager:start step-security-hosts
      # @config-manager:end step-security-hosts

      # @config-manager:start workflow-clone
      # @config-manager:end workflow-clone

      # @config-manager:start workflow-analysis
      # @config-manager:end workflow-analysis

      # @config-manager:start workflow-upload
      # @config-manager:end workflow-upload

      # @config-manager:start workflow-upload-codeql
      # @config-manager:end workflow-upload-codeql
