---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

# @config-manager:start workflow-name
# @config-manager:end workflow-name

on:
  # @config-manager:start workflow-on
  # @config-manager:end workflow-on

concurrency:
  # @config-manager:start workflow-concurrency
  # @config-manager:end workflow-concurrency

# Declare default permissions as read only.
# @config-manager:start workflow-permissions
# @config-manager:end workflow-permissions

jobs:
  update_on_push_job:
    # @config-manager:start update-on-push-job
    # @config-manager:end update-on-push-job
    steps:
      # @config-manager:start harden-runner
      fake1:
        fake2:
          # @config-manager:end harden-runner
          allowed-endpoints: >
            # @config-manager:start step-security-hosts
            # @config-manager:end step-security-hosts

      # @config-manager:start workflow-run-steps
      # @config-manager:end workflow-run-steps
