[tools]
1password-cli = "latest"
action-validator = "latest"
actionlint = "latest"
amazon-ecr-credential-helper = "latest"
aqua = "latest"
"aqua:minamijoyo/tfschema" = "latest"
atlas = "latest"
aube = "latest"
aws-vault = "latest"
awsweeper = "latest"
bat = "latest"
bats = "latest"
buf = "latest"
claude-code = "latest"
cloudflared = "latest"
copilot = "latest"
coreutils = "latest"
cosign = "latest"
deno = "latest"
devcontainer-cli = "latest"
direnv = "latest"
dive = "latest"
docker-compose = "latest"
dotenvx = "latest"
driftctl = "latest"
duckdb = "latest"
editorconfig-checker = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
gh = "latest"
ghalint = "latest"
git-cliff = "latest"
git-filter-repo = "latest"
git-lfs = "latest"
github-cli = "latest"
glow = "latest"
go = "latest"
gofumpt = "latest"
golangci-lint = "latest"
golines = "latest"
goreleaser = "latest"
gotestsum = "latest"
grpcurl = "latest"
grype = "latest"
gum = "latest"
hadolint = "latest"
hk = "latest"
hugo = "latest"
hyperfine = "latest"
infracost = "latest"
jq = "latest"
jsonschema = "latest"
lefthook = "latest"
lychee = "latest"
mockery = "latest"
node = "latest"
oapi-codegen = "latest"
ollama = "latest"
opa = "latest"
opengrep = "latest"
opentofu = "latest"
osv-scanner = "latest"
packer = "latest"
pandoc = "latest"
pitchfork = "latest"
podman = "latest"
prettier = "latest"
protobuf = "latest"
protoc = "latest"
protoc-gen-connect-go = "latest"
protoc-gen-go = "latest"
protoc-gen-go-grpc = "latest"
python = "latest"
rg = "latest"
ruff = "latest"
rumdl = "latest"
rust = "latest"
rust-analyzer = "latest"
scorecard = "latest"
sentinel = { version = "latest", url = 'https://releases.hashicorp.com/sentinel/{{ version }}/sentinel_{{ version }}_{{ os(macos="darwin") }}_{{ arch(x64="amd64") }}.zip', version_expr = "fromJSON(body).versions | keys() | sortVersions()", version_list_url = "https://releases.hashicorp.com/sentinel/index.json" }
shellcheck = "latest"
shfmt = "latest"
spectral = "latest"
sqlc = "latest"
steampipe = "latest"
swiftformat = { version = "latest", no_app = "true", rename_exe = "swiftformat" }
syft = "latest"
tailpipe = "latest"
taplo = "latest"
task = "latest"
tbls = "latest"
terraform = "latest"
terraform-docs = "latest"
terragrunt = "latest"
terramate = "latest"
tf-summarize = "latest"
tflint = "latest"
tfmigrate = "latest"
tfstate-lookup = "latest"
tilt = "latest"
tree-sitter = "latest"
trivy = "latest"
trufflehog = "latest"
usage = "latest"
uv = "latest"
vhs = "latest"
yamlfmt = "latest"
