---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

# @config-manager:start workflow-name
name: Generate CHANGELOG on push
# @config-manager:end workflow-name

# @config-manager:start workflow-on
on:
  workflow_dispatch:
  push:
    branches:
      - main
# @config-manager:end workflow-on

# @config-manager:start workflow-permissions
# Declare default permissions as read only.
permissions: read-all
# @config-manager:end workflow-permissions

jobs:
  update_on_push_job:
    # @config-manager:start update-on-push-job
    runs-on: ubuntu-latest
    name: Generate CHANGELOG on push
    timeout-minutes: 2
    # @config-manager:end update-on-push-job
    permissions:
      # @config-manager:start workflow-permissions-job
      contents: write
      # @config-manager:end workflow-permissions-job
    steps:
      # @config-manager:start workflow-install-node
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "26"
          token: ${{ secrets.GITHUB_TOKEN }}
      # @config-manager:end workflow-install-node

      # @config-manager:start workflow-gen-changelog
      - name: Generate Changelog
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      # @config-manager:end workflow-gen-changelog

      # @config-manager:start workflow-cleanup
      - name: Remove git-cliff artifacts
        run: |
          rm -Rf git-cliff*
      # @config-manager:end workflow-cleanup

      # @config-manager:start workflow-contributors
      - name: Generate artifacts
        run: |
          # Generate list of authors
          ./scripts/generate-contributors.sh
      # @config-manager:end workflow-contributors

      # @config-manager:start workflow-commit
      - name: Git commit if changed
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          git config user.name "Northwood Labs (Bot)"
          git config user.email "bot@northwood-labs.com"

          set +e

          git add .
          git status | grep modified
          if [ $? -eq 0 ]; then
            git commit -a -m "automation: Updated AUTHORS and CHANGELOG on $(date)."
            git pull --rebase --autostash
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main
          fi
      # @config-manager:end workflow-commit
