[tools]
  # @config-manager:start terraform
  "aqua:minamijoyo/tfschema" = "0.7.10"
  driftctl = "0.40.0"
  infracost = "0.10.44"
  opa = "1.16.1"
  opentofu = "1.11.6"
  terraform = "1.15.2"
  terraform-docs = "0.23.0"
  terragrunt = "1.0.3"
  terramate = "0.16.0"
  tf-summarize = "0.3.20"
  tflint = "0.62.0"
  tfmigrate = "0.4.5"
  tfstate-lookup = "1.11.0"
  # @config-manager:end terraform
