#-------------------------------------------------------------------------------
# HEADING RULES

# @config-manager:start headings
# @config-manager:end headings

#-------------------------------------------------------------------------------
# LIST RULES

# @config-manager:start lists
# @config-manager:end lists

#-------------------------------------------------------------------------------
# WHITESPACE RULES

# @config-manager:start whitespace
# @config-manager:end whitespace

#-------------------------------------------------------------------------------
# FORMATTING RULES

# @config-manager:start formatting
# @config-manager:end formatting

# https://rumdl.dev/md044/
[MD044]
  # proper-names
  enabled = true
  code-blocks = false
  html-elements = false
  html-comments = true
  names = [
    # @config-manager:start proper-names
    # @config-manager:end proper-names
  ]

#-------------------------------------------------------------------------------
# CODE BLOCK RULES

# @config-manager:start code-block
# @config-manager:end code-block

#-------------------------------------------------------------------------------
# LINK AND IMAGE RULES

# @config-manager:start link-image
# @config-manager:end link-image

#-------------------------------------------------------------------------------
# TABLE RULES

# @config-manager:start tables
# @config-manager:end tables

#-------------------------------------------------------------------------------
# FOOTNOTE RULES

# @config-manager:start footnotes
# @config-manager:end footnotes

#-------------------------------------------------------------------------------
# FRONTMATTER RULES

# @config-manager:start frontmatter
# @config-manager:end frontmatter

#-------------------------------------------------------------------------------
# OTHER RULES

# @config-manager:start other
# @config-manager:end other

#-------------------------------------------------------------------------------
# GLOBAL CONFIG

[global]
  # @config-manager:start globals
  # @config-manager:end globals
  exclude = [
    # @config-manager:start globals-excludes
    # @config-manager:end globals-excludes
  ]
