---
name: "🛠️ Standard Settings"
on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository name"
        required: true
        type: choice
        options:
          # Need to automate this.
          # gh repo list northwood-labs --no-archived --source --visibility public --limit 200 --json name | jq -Mr '[.[].name] | sort | .[] | "          - \(.)"'
          - .github
          - assume-spoke-role
          - aws-account-list
          - aws-config-parser
          - aws-mcp-credential-proxy
          - aws-service-models
          - aws-sso-manager
          - branding
          - cli-helpers
          - crowdstrike-falcon-downloader
          - csp-parser
          - devsec-tools
          - devsec-tools-sdk-go
          - devsec-tools-sdk-php
          - devsec-tools-sdk-ts
          - devsec-ui
          - discussions
          - download-asset
          - git-gen
          - git-mirrors
          - go-x-perf
          - go.nwlabs.dev
          - gocache-valkey
          - hcl-formatter
          - homebrew-tap
          - hugo-dst2024
          - lambda-provided-al2023
          - lintbrush
          - local-lambda-environments-with-go
          - macos-for-development
          - mod-aws-networking
          - mod-aws-resource-tags
          - northwood-labs.github.io
          - opentofu-support
          - package-building
          - password-complexity-evaluator
          - privacy-policy
          - reviewdog
          - ssm-shell
          - terms-of-service
          - terraform-provider-corefunc
          - tflint-config-generator
          - tomlrt-cli
          - vendor-icons
          - x

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

# env:

permissions: read-all

jobs:
  lookup:
    runs-on: ubuntu-latest
    name: Apply Standard Settings (${{ inputs.repo }})
    permissions:
      contents: read
    strategy:
      fail-fast: false

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Git clone
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: ${{ github.base_ref }}
          persist-credentials: false

      - name: Setup Go environment
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ">= 1.22.1"

      - name: Apply
        working-directory: ${{ github.workspace }}/scripts/standard-settings
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUBLIC_TOKEN }}
        run: |
          go run standard-settings.go --repo ${{ inputs.repo }}
